name: Hello World

env:
  USERNAME: "april"
  PASSWORD: "hellosecure"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy"
        required: true
        default: "dev"
        type: choice
        options: ["dev", "staging", "prod"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the OS name 
        run: lslp
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: build
    steps:
      - name: Docker Run
        run: |
          echo "hello"
          ls -l
          sleep 60s
