name: Hello World

env:
  USERNAME: "april"
  PASSWORD: "hellosecure"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy"
        required: true
        default: "dev"
        type: choice
        options: ["dev", "staging", "prod"]

jobs:
  first_job:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        images: [hello-world, alpine]
        exclude:
        - os: windows-latest
          image: alpine
        include: 
        - os: macos-latest
          image: scratch
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo the OS name 
        run: echo "Hello from ${{ matrix.os }}"
      - name: Echo the name of the image
        run: echo "Hello from ${{ matrix.images }}"
    
