name: Hello World

env:
  USERNAME: "april"
  PASSWORD: "hellosecure"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy"
        required: true
        default: "dev"
        type: choice
        options: ["dev", "staging", "prod"]

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo text
        run: echo "Hello, world!"
  deploy:
    concurrency:
      group: deploy-${{ github.ref_name }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, ${{ github.ref_name }}!"
      - name: sleep 5 minutes
        run: sleep 300s
