name: Push Tags
permissions:
  contents: write
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy To: "
        required: true
        default: "dev"
        type: environment
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Source Code
         uses: actions/checkout@v4
      
       - name: Create Tag
         if: (github.ref_name == 'main' || github.ref_name == 'release') 
         run: |
           echo TAG = "v${GITHUB_SHA::6}" > GITHUB_ENV
           echo "Tag: $TAG"
           git tag $TAG
           git push origin $TAG
           
         #  git config user.name "github-actions"
         #  git config user.email "github-actions@github.com"

