name: Push Tags
permissions:
  contents: write
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy To: "
        required: true
        default: "dev"
        type: environment
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Source Code
         uses: actions/checkout@v4
      
       - name: Create Tag
         if: (github.ref_name == 'main' || github.ref_name == 'release') 
         run: |
             echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
             git tag -a "commit-${{ env.SHORT_SHA }}" -m "Tagging commit ${{ github.sha }}"
             # Push the specific tag to the remote
             git push origin "${{ env.SHORT_SHA }}"
                        
        # git config user.name "github-actions"
        # git config user.email "github-actions@github.com"
          


